name: Update Projects JSON

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 11:30 AM IST
  workflow_dispatch: # Allows manual trigger via GitHub UI

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run project update script
        run: python .github/scripts/update_projects.py

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add projects.json
          git diff --cached --quiet || git commit -m "Auto-update projects.json"
          git push
